[book]
authors = ["Paul Alesius"]
language = "en"
multilingual = false
src = "src"
title = "Large Language Math - The Mathematics of LLM Foundational Models - For Beginners"

[build]
# Careful calling mdbook with "mdbook -d <path>" as it will delete the path
build-dir = "book"

[output.html]
mathjax-support = true
theme = "theme"
