[book]
authors = ["Paul Alesius"]
language = "en"
multilingual = false
src = "src"
title = "Large Language Math - The Mathematics of LLM Foundational Models - For Beginners"

[build]
build-dir = "book"
