#+TITLE: Algebraic Expressions

* Introduction
  Algebraic expressions are combinations of variables, constants, and operations. In this section, we will explore how these expressions are formed and manipulated.

* Algebraic Expressions
** Definition
   An algebraic expression is a mathematical phrase that can contain ordinary numbers, variables (like x or y) and operators (like add, subtract, multiply, and divide).

** Components of an Expression
   - /Variables/: Symbols that represent numbers. E.g., x, y, z.
   - /Constants/: Fixed values. E.g., 3, -5, 2/3.
   - /Operators/: Symbols that represent operations. E.g., + (addition), - (subtraction), * (multiplication), / (division).

** Examples of Expressions
   - \( 3x + 4 \)
   - \( 5y - 7 \)
   - \( 2x^2 + 3x - 5 \)

* Simple Operations in R
  We will use R to perform some basic operations on algebraic expressions.

** Addition Example
   #+BEGIN_SRC R
   x <- 2 # Assign a value to x
   expression <- 3 * x + 4
   print(expression)
   #+END_SRC

** Subtraction Example
   #+BEGIN_SRC R
   y <- 5 # Assign a value to y
   expression <- 5 * y - 7
   print(expression)
   #+END_SRC

** Polynomial Example
Polynomials will be explained in further chapters, but it's also an expression.
   #+BEGIN_SRC R
   x <- 1 # Assign a value to x
   expression <- 2 * x^2 + 3 * x - 5
   print(expression)
   #+END_SRC

* Conclusion
  Understanding algebraic expressions is fundamental in algebra. They form the basis for more complex topics like equations, functions, and beyond.
